import mongoose from "mongoose";

const videoData = [ 
    {  
        "title": "Learn React in 30 Minutes", 
        "thumbnailUrl": "https://img.youtube.com/vi/hQAHSlTtcmY/hqdefault.jpg", 
        "description": "A quick tutorial to get started with React.",
        "channelId": new mongoose.Types.ObjectId("67ab60ceacb7adb7225b009d"), 
        "uploader": "viraj2001", 
        "views": 15200, 
        "likes": [],
        "dislikes": [], 
        "uploadDate": "2024-09-20",
        "videoUrl" : 'https://www.youtube.com/embed/hQAHSlTtcmY',
    },
    {
        "title": "JavaScript ES6 Features Explained",
        "thumbnailUrl": "https://img.youtube.com/vi/NCwa_xi0Uuc/hqdefault.jpg",
        "description": "Learn the latest ES6 features in JavaScript.",
        "channelId": new mongoose.Types.ObjectId("67ab60ceacb7adb7225b009d"),
        "uploader": "viraj2001",
        "views": 22450,
        "likes": [],
        "dislikes": [],
        "uploadDate": "2024-08-15",
        "videoUrl" : 'https://www.youtube.com/embed/NCwa_xi0Uuc',
    },
    {
        "title": "CSS Flexbox & Grid - Full Course",
        "thumbnailUrl": "https://img.youtube.com/vi/ieTHC78giGQ/hqdefault.jpg",
        "description": "Master CSS Flexbox and Grid layout with this full course.",
        "channelId": new mongoose.Types.ObjectId("67ab60ceacb7adb7225b009d"),
        "uploader": "viraj2001",
        "views": 18900,
        "likes": [],
        "dislikes": [],
        "uploadDate": "2024-07-12",
        "videoUrl" : 'https://www.youtube.com/embed/ieTHC78giGQ',
    },
    {
        "title": "Node.js Crash Course",
        "thumbnailUrl": "https://img.youtube.com/vi/32M1al-Y6Ag/hqdefault.jpg",
        "description": "A beginner-friendly crash course on Node.js.",
        "channelId": new mongoose.Types.ObjectId("67ab60ceacb7adb7225b009d"),
        "uploader": "viraj2001",
        "views": 30500,
        "likes": [],
        "dislikes": [],
        "uploadDate": "2024-06-18",
        "videoUrl" : 'https://www.youtube.com/embed/32M1al-Y6Ag',
    },
    {
        "title": "MongoDB Tutorial for Beginners",
        "thumbnailUrl": "https://img.youtube.com/vi/J6mDkcqU_ZE/hqdefault.jpg",
        "description": "Get started with MongoDB, NoSQL database tutorial.",
        "channelId": new mongoose.Types.ObjectId("67ab60ceacb7adb7225b009d"),
        "uploader": "viraj2001",
        "views": 18500,
        "likes": [],
        "dislikes": [],
        "uploadDate": "2024-05-25",
        "videoUrl" : 'https://www.youtube.com/embed/J6mDkcqU_ZE',
    },
    {
        "title": "Python for Data Science - Full Course",
        "thumbnailUrl": "https://img.youtube.com/vi/yGN28LY5VuA/hqdefault.jpg",
        "description": "A complete Python Data Science course for beginners.",
        "channelId": new mongoose.Types.ObjectId("67ab60ceacb7adb7225b009d"),
        "uploader": "viraj2001",
        "views": 67000,
        "likes": [],
        "dislikes": [],
        "uploadDate": "2024-04-10",
        "videoUrl" : 'https://www.youtube.com/embed/yGN28LY5VuA',
    },
    {
        "title": "React Hooks Explained",
        "thumbnailUrl": "https://img.youtube.com/vi/LOH1l-MP_9k/hqdefault.jpg",
        "description": "Learn React Hooks and how to use them effectively.",
        "channelId": new mongoose.Types.ObjectId("67ab60ceacb7adb7225b009d"),
        "uploader": "viraj2001",
        "views": 19200,
        "likes": [],
        "dislikes": [],
        "uploadDate": "2024-03-22",
        "videoUrl" : 'https://www.youtube.com/embed/LOH1l-MP_9k',
    },
    {
        "title": "Docker & Kubernetes - Full Course",
        "thumbnailUrl": "https://img.youtube.com/vi/Wf2eSG3owoA/hqdefault.jpg",
        "description": "Learn how to use Docker and Kubernetes in production.",
        "channelId": new mongoose.Types.ObjectId("67ab60ceacb7adb7225b009d"),
        "uploader": "viraj2001",
        "views": 59000,
        "likes": [],
        "dislikes": [],
        "uploadDate": "2024-02-05",
        "videoUrl" : 'https://www.youtube.com/embed/Wf2eSG3owoA',
    },
    {
        "title": "Git & GitHub for Beginners",
        "thumbnailUrl": "https://img.youtube.com/vi/RGOj5yH7evk/hqdefault.jpg",
        "description": "Master Git and GitHub with this beginner tutorial.",
        "channelId": new mongoose.Types.ObjectId("67ab60ceacb7adb7225b009d"),
        "uploader": "viraj2001",
        "views": 32000,
        "likes": [],
        "dislikes": [],
        "uploadDate": "2024-01-20",
        "videoUrl" : 'https://www.youtube.com/embed/RGOj5yH7evk',
    },
    {
        "title": "Machine Learning Basics",
        "thumbnailUrl": "https://img.youtube.com/vi/ukzFI9rgwfU/hqdefault.jpg",
        "description": "A beginner's introduction to Machine Learning.",
        "channelId": new mongoose.Types.ObjectId("67ab60ceacb7adb7225b009d"),
        "uploader": "viraj2001",
        "views": 45500,
        "likes": [],
        "dislikes": [],
        "uploadDate": "2023-12-10",
        "videoUrl" : 'https://www.youtube.com/embed/ukzFI9rgwfU',
    },
    {
        "title": "Vue.js 3 - Complete Guide",
        "thumbnailUrl": "https://img.youtube.com/vi/nhBVL41-_Cw/hqdefault.jpg",
        "description": "A full guide to Vue.js 3 and its ecosystem.",
        "channelId": new mongoose.Types.ObjectId("67ab60ceacb7adb7225b009d"),
        "uploader": "viraj2001",
        "views": 23800,
        "likes": [],
        "dislikes": [],
        "uploadDate": "2023-11-05",
        "videoUrl" : 'https://www.youtube.com/embed/nhBVL41-_Cw',
    },
    {
        "title": "Advanced JavaScript Concepts",
        "thumbnailUrl": "https://img.youtube.com/vi/lkIFF4maKMU/hqdefault.jpg",
        "description": "Deep dive into JavaScript advanced topics.",
        "channelId": new mongoose.Types.ObjectId("67ab60ceacb7adb7225b009d"),
        "uploader": "viraj2001",
        "views": 28700,
        "likes": [],
        "dislikes": [],
        "uploadDate": "2023-10-15",
        "videoUrl" : 'https://www.youtube.com/embed/lkIFF4maKMU',
    },
    {
        "title": "SQL Database Design Tutorial",
        "thumbnailUrl": "https://img.youtube.com/vi/MiAl2mQ718s/hqdefault.jpg",
        "description": "Learn how to design and optimize SQL databases.",
        "channelId": new mongoose.Types.ObjectId("67ab60ceacb7adb7225b009d"),
        "uploader": "viraj2001",
        "views": 17800,
        "likes": [],
        "dislikes": [],
        "uploadDate": "2023-09-05",
        "videoUrl" : 'https://www.youtube.com/embed/MiAl2mQ718s',
    },
    {
        "title": "Web Development Roadmap 2024",
        "thumbnailUrl": "https://img.youtube.com/vi/GxmfcnU3feo/hqdefault.jpg",
        "description": "A roadmap to becoming a full-stack developer.",
        "channelId": new mongoose.Types.ObjectId("67ab60ceacb7adb7225b009d"),
        "uploader": "viraj2001",
        "views": 38200,
        "likes": [],
        "dislikes": [],
        "uploadDate": "2023-08-25",
        "videoUrl" : 'https://www.youtube.com/embed/GxmfcnU3feo',
    },
    {
        "title": "Cybersecurity Essentials",
        "thumbnailUrl": "https://img.youtube.com/vi/aRbKFCY4tjE/hqdefault.jpg",
        "description": "Introduction to cybersecurity and ethical hacking.",
        "channelId": new mongoose.Types.ObjectId("67ab60ceacb7adb7225b009d"),
        "uploader": "viraj2001",
        "views": 45000,
        "likes": [],
        "dislikes": [],
        "uploadDate": "2023-07-10",
        "videoUrl" : 'https://www.youtube.com/embed/aRbKFCY4tjE',
    }
]

export default videoData;